### ISSUE TITLE
CI to validate BioImage.IO packages on zenodo 

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#2]
we currently have a javascript script to scrape zenodo for bioimage.io community records.

To get to a CI running syntax and full tests (test inputs produce test outputs) we need:
- [x] keep scraped collection of zenodo models up to date (see #1 )
- [x] generate a test summary for all models (using bioimageio.spec for static...
- [x] ...and bioimageio.core for full tests -> #7 
- [ ] make sure tests are only run on changes (identify each record by its doi) -> saved for later: #8 

@oeway @constantinpape @k-dominik @emilmelnikov

**Comment by FynnBe** [comment]
@oeway the CI now also generates https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/validation_summary.yaml

entries are keyed by <id>,<python version>,<bioimageio.spec version>,<bioimageio.core version = None for now>
if errors is an empty list the model is valid.

We are thinking of changing `errors` to `static_errors` and add `dynamic_errors` for the tests with test input output.. I'll make a new PR for that...
